### PR TITLE
Adding .idea folder to the .gitignore

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shvachko** [comment]
+1
Let's make sure we follow the commit message format pattern. This one should say:
Issue 101: Adding .idea folder to the .gitignore. (Cos)

**Comment by shvachko** [comment]
And we still updating CHANGES.txt with each commit. May need to add new section for 0.1.1 release.

**Comment by ghost** [comment]
Thanks, Two points about CHANGES.txt
1.  shall it be done about trivial non-product changes like this?
2.  manual update of the changes could be optimised and done automatically. What we do in Bigtop is simply grabbing the list of the issues addressed in the release and populate the changes file in one set. IMO it is less painful and way easier as RE is doing this usually. 

What do you  think?

**Comment by shvachko** [comment]
We routinely do this for all changes, without distinguishing between small or big, trivial or not.
We can get rid of CHANGES.txt, which is redundant, given the commit messages allow restoring issue numbers.
Let's make an issue for removing CHANGES.txt. We should also add pre-commit hook in that jira, which enforces the commit message format.

**Comment by shvachko** [comment]
Committed. Thank you Cos.

**Pull request closed without merging**
