### PR TITLE
Issue 156: Introduce GiraffaConfiguration.getGiraffaTableName() (weilin)

### PR DESCRIPTION
**Pull request by weilintsaiWand**
Refactor code to fix Issue 156. I am not contributor now so just create a pull request. All existing unit tests passed.

### CODE REVIEW

**Comment by milandesai** [comment]
Good work Wei-Lin!

**Comment by weilintsaiWand** [comment]
link to #156

**Comment by weilintsaiWand** [comment]
Refine a line of code in GiraffaTestUtils.java to use new method in the 2nd commit.

**Comment by shvachko** [comment]
Guys, the comments should go into the issue itself, not the pull request. This is to assure all information is in one place.

**Pull request closed without merging**
